---
- hosts: javaserver
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvar3: apache2
  tasks:
    - name: Display the value of myvar3
      debug:
        msg: "{{ myvar3 }}"

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ myvar1 }}"
        - "{{ myvar2 }}"
        - "{{ myvar3 }}"
      register: install_result

    - name: Check for installation errors
      debug:
        msg: "Package installation result: {{ install_result }}"
